# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 17:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100, verbose_name='Name product')),
                ('slug_category', models.SlugField(max_length=100, verbose_name='Slug')),
                ('title_category_seo', models.CharField(max_length=200)),
                ('image_category', models.ImageField(blank=True, default=None, null=True, upload_to='images/category_images')),
                ('description_category', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('active_category', models.BooleanField(default=True, verbose_name='Active category')),
                ('keywords_category_seo', models.TextField(verbose_name='Keywords seo site')),
                ('description_category_seo', models.TextField(verbose_name='Description seo site')),
                ('parent_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.CategoryProducts')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
