# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_manufactures', models.CharField(max_length=150, verbose_name='Name manufactures')),
                ('slug_manufactures', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL')),
                ('site_manufacturas', models.URLField(verbose_name='URL Manufactures')),
                ('logo_manufactures', models.ImageField(blank=True, default=None, null=True, upload_to='images/manufactures_logo', verbose_name='Logo manufactures')),
            ],
            options={
                'db_table': 'manufactures',
            },
        ),
        migrations.CreateModel(
            name='ManufacturesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat_manufactures', models.CharField(max_length=50, verbose_name='Category manufactures')),
            ],
            options={
                'db_table': 'man_category',
            },
        ),
        migrations.AlterField(
            model_name='categoryproducts',
            name='image_category',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/category_images', verbose_name='Image category'),
        ),
        migrations.AlterField(
            model_name='categoryproducts',
            name='name_category',
            field=models.CharField(max_length=100, verbose_name='Name category'),
        ),
        migrations.AlterField(
            model_name='categoryproducts',
            name='slug_category',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='categoryproducts',
            name='title_category_seo',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manufactures',
            name='category_manufactures',
            field=models.ManyToManyField(to='magazine.ManufacturesCategory', verbose_name='Category manufactures'),
        ),
    ]
