# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 04:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20170605_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=200, verbose_name='Name product')),
                ('code_product', models.CharField(max_length=100, verbose_name='Code product')),
                ('prise_product', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prise product')),
                ('slug_product', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL')),
                ('base_image_product', models.ImageField(blank=True, default=None, null=True, upload_to='images/product_image', verbose_name='Base image')),
                ('description_product', ckeditor.fields.RichTextField(verbose_name='Description product')),
                ('title_product_seo', models.CharField(max_length=150, verbose_name='Title SEO')),
                ('description_seo', models.TextField(verbose_name='SEO description')),
                ('keywords_seo', models.TextField(verbose_name='SEO keywords')),
                ('active_product', models.BooleanField(default=True, verbose_name='Active product')),
                ('rating_product', models.PositiveIntegerField(default=0, verbose_name='Rating product')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AlterField(
            model_name='categoryproducts',
            name='description_category',
            field=ckeditor.fields.RichTextField(verbose_name='Description category'),
        ),
        migrations.AddField(
            model_name='products',
            name='category_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.CategoryProducts', verbose_name='Category product'),
        ),
        migrations.AddField(
            model_name='products',
            name='manufactures_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.Manufactures'),
        ),
    ]
