# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20170607_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactures',
            name='site_manufacturas',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='URL Manufactures'),
        ),
    ]
