# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20170607_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/gallery_image', verbose_name='Gallery image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.Products')),
            ],
            options={
                'db_table': 'gallery_image',
            },
        ),
    ]
